<?php
    /**
     * Copyright © 2017 Codazon, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */
?>
<?php
$helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
$linksList = $helper->getConfig('themelayoutpro/header/left_menu');
?>

<?php if ($linksList) : ?>
<div class="links-list">
<?php
    echo $block->getLayout()->createBlock('Codazon\MegaMenu\Block\Widget\Megamenu')
        ->setMenu($linksList)
        ->setData('menu_type', 1)
        ->toHtml();
?>
</div>
<?php endif ?>