<?php
    /**
     * Copyright © 2017 Codazon, Inc. All rights reserved.
     * See COPYING.txt for license details.
     */
?>
<?php $childBlocks = $block->getChildNames(); ?>


<div class="utilies-panel" ng-controller="UtilitiesPanelCtrl" layout="column" ng-cloak>
    <section layout="row" flex class="panel-outer">
        <md-sidenav md-disable-scroll-target class="<?php echo $block->getData('css_class'); ?> panel-inner" md-component-id="<?php echo $block->getData('component_id'); ?>" md-whiteframe="4">
            <?php if ($block->getData('label')) : ?>
            <md-toolbar class="md-theme-indigo">
                <h1 class="md-toolbar-tools"><?php echo $block->getData('label'); ?></h1>
            </md-toolbar>
            <?php endif ?>
            <md-content class="utilies-sections">
                <?php
                if ($requiredBlocks = $block->getData('required_blocks')) {
                    $helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
                    foreach($requiredBlocks as $action => $childName) {
                        if (method_exists($helper, $action)) {
                            if ($helper->{$action}() != 'sidebar') {
                                unset($requiredBlocks[$action]);
                            }
                        }
                    }
                    $childBlocks = array_unique(array_merge($requiredBlocks, $childBlocks));
                }
                ?>
                <?php if ($childBlocks) : ?>
                <?php $active = 'active'; ?>
                <?php foreach ($childBlocks as $childName) : ?>
                <?php $child = $block->getLayout()->getBlock($childName); ?>
                <div class="utilies-section <?php echo $active ?> <?php echo $child->getData('css_class') ?>" <?php echo $child->getData('html_id')?'id="'.$child->getData('html_id').'"':''; ?> >
                    <?php echo $child->toHtml() ?>
                </div>
                <?php $active = ''; ?>
                <?php endforeach ?>
                <?php endif ?>
            </md-content>
        </md-sidenav>
    </section>
</div>