<?php
/**
 * Sunbrains
 * @category  Sunbrains
 * @package   Sunbrains_SMSProfile
 * @author    Sunbrains
 */
 
/**
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<?php 
    $smsProfileHelper = $this->helper('Sunbrains\SMSProfile\Helper\Data');
    $required = 0;
    $validate = $smsProfileHelper->getSmsProfileMailPhoneValidationClass();
    if ($smsProfileHelper->getModuleStatus()) {
        $required = 1;
    }
?>
<form class="form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <?php if(!$required) { ?>
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?></div>
        <?php } else { ?>
            <div class="field note"><?= $block->escapeHtml(__('Please enter your email address or telephone below to receive a password reset link.')) ?></div>
        <?php } ?>    
        <div class="field email required">
            <?php if(!$required) { ?>
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
             <?php } else { ?> 
                  <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email or Telephone')) ?></span></label>  
             <?php }  ?>
            <div class="control">
                <input <?php if(!$required) { echo 'type="email"';} else { echo 'type="text"'; } ?> name="email" alt="email" id="email_address" class="input-text <?php if($required) { echo $validate;} ?>" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{},"validation":{}}' data-validate="{required:true,  <?php if(!$required) { echo '\'validate-email\':true'; }?>}">
            </div>
            
            <?php if($required) { ?>
                <?php if($smsProfileHelper->getPhoneNote()) { ?>
                <div class="profile-notice-phone">
                    <span><?php echo $smsProfileHelper->getPhoneNote(); ?></span>
                </div> 
                <?php } ?>
                <div class="field">
                    <button class="send_otp_password action primary" style="display: none;margin-top: 15px;" type="button"><?php echo __('Generate OTP');?></button>
                </div> 
                <?php 
                $sendOtpUrl = $this->getUrl('smsprofile/otp/send');
                $verifyOtpUrl = $this->getUrl('smsprofile/otp/verify');
                echo "<input type='hidden' class='sendUrlforget' value='".$sendOtpUrl."'/>";
                echo "<input type='hidden' class='verifyUrlforget' value='".$verifyOtpUrl."'/>";
                echo "<input type='hidden' class='forgetOtpValidation' name = 'forgetOtpValidation' value='0'/>";
            }?>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Go back')) ?></span></a>
        </div>
    </div>
</form>
