<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>

<?php if ($block->getMode() == 'grid') : ?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
<?php
/* helper */
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$imageHelper = $this->helper('Magento\Catalog\Helper\Image');
$themeHelper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
$quickShopHelper = $this->helper('Codazon\QuickShop\Helper\Data');
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$wishlistHelper = $this->helper('Magento\Wishlist\Helper\Data');
$labelHelper = $this->helper('Codazon\ProductLabel\Helper\Data');

/* layout */
$layout = $themeHelper->getBlockPageLayout($block);

/* show on list */
$showDescription = $themeHelper->isDisplayOnList('description');
$showSku = $themeHelper->isDisplayOnList('sku');
$showWishlist = $themeHelper->isDisplayOnList('wishlist');
$showCompare = $themeHelper->isDisplayOnList('compare');
$showCart = $themeHelper->isDisplayOnList('addtocart');
$showQuickShop = $themeHelper->isDisplayOnList('quickshop');
$showLabel = $themeHelper->isDisplayOnList('label');
$showThumb = $themeHelper->isDisplayOnList('thumb');
$showName = $themeHelper->isDisplayOnList('name');
$showReview = $themeHelper->isDisplayOnList('review');
$showPrice = $themeHelper->isDisplayOnList('price');



$width = $themeHelper->getConfig('images/category/product_image_width')?:150;
$height = $themeHelper->getConfig('images/category/product_image_height')?:150;
$paddingBottom = $height*100/$width;

$cartWidget = $block->isRedirectToCartEnabled()?'':'data-mage-init=\'{"catalogAddToCart":{}}\'';
?>
<style type="text/css">
<?= $themeHelper->getColumnStyle('.page-products .products-grid .product-items', '.page-products .products-grid .product-items .item.product-item', '.page-products .product-items .item.product-item', $layout); ?>
</style>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
	$viewMode = 'grid';
	$image = 'category_page_grid';
	$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
	
    <div class="products wrapper product-list-style-04 <?= $viewMode ?> products-<?= $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items flex-grid">
            <?php foreach ($_productCollection as $_product): ?>
                <?= ($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php if ($showThumb) : ?>
                    <?php
						$mainImage = $_product->getData('small_image');
						$hoveredImage = $_product->getData('thumbnail');
                    ?>
                    <div class="product-item-top">
                        <a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo">
                            <span class="product-image-container">
                                <span class="product-image-wrapper" style="padding-bottom: <?= $paddingBottom ?>%;">
                                    <img class="product-image-photo main-img" src="<?php echo $imageHelper->init($_product, $image)->setImageFile($mainImage)->resize($width, $height)->getUrl() ?>" />
                                    <img class="product-image-photo hovered-img" src="<?php echo $imageHelper->init($_product, $image)->setImageFile($hoveredImage)->resize($width, $height)->getUrl() ?>" />
                                </span>
                            </span>
                        </a>
                        <?= $showQuickShop?$quickShopHelper->getQuickShopButton($_product):''; ?>
                        <?= $showLabel?$labelHelper->showLabel($_product):''; ?>
                    </div>
                    <?php endif ?>
                    <div class="product details product-item-details">
						<?php if ($showName): ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $_product->getProductUrl() ?>">
                                <?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
						<?php endif ?>
						<?php if ($showSku) : ?>
                            <div class="product-item-sku"><span class="label"><?= __('SKU: ') ?></span><span class="value"><?= $_product->getData('sku') ?></span></div>
						<?php endif ?>
                        <?= $showReview?$block->getReviewsSummaryHtml($_product, $templateType):'' ?>
                        <?= $showPrice?$block->getProductPrice($_product):'' ?>
                        <?= $block->getProductDetailsHtml($_product) ?>
						<?php if ($showDescription):?>
						<div class="product description product-item-description">
							<?= $themeHelper->subString($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'), 60) ?>
						</div>
						<?php endif; ?>
                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <?php if ($showCart) : ?>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form <?= $cartWidget ?> data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= Action::PARAM_NAME_URL_ENCODED ?>" value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
											<button onclick="document.location.href = '<?= $_product->getProductUrl(); ?>'" class="action tocart primary stock available"><span><?= __('In stock') ?></span></button>
										<?php else: ?>
											<button class="action tocart primary disabled stock unavailable" disabled><span><?= __('Out of stock') ?></span></button>
										<?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?php endif ?>
								<?php if ($showWishlist || $showCompare): ?>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($wishlistHelper->isAllow() && $showWishlist): ?>
										<a href="#"
										   data-post='<?= $block->getAddToWishlistParams($_product); ?>'
										   class="action towishlist" data-action="add-to-wishlist"
										   title="<?= __('Add to Wish List') ?>">
											<span><?= __('Add to Wish List') ?></span>
										</a>
									<?php endif; ?>
									<?php if ($block->getAddToCompareUrl() && $showCompare): ?>
										<a href="#" class="action tocompare"
										   data-post='<?= $compareHelper->getPostDataParams($_product);?>'
										   title="<?= __('Add to Compare') ?>">
											<span><?= __('Add to Compare') ?></span>
										</a>
									<?php endif; ?>
                                </div>
								<?php endif ?>
                            </div>
                        </div>
                    </div>
                </div>
                <?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
<?php endif; ?>
<?php else : ?>
<?php echo $this->setTemplate('Magento_Catalog::product/list/list-mode/list.phtml')->toHtml(); ?>
<?php endif ?>