<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
$uid = uniqid('product-tabs-');
$helper = $this->helper('Codazon\ThemeLayoutPro\Helper\Data');
$detailedInfoGroup = $block->getGroupChildNames('detailed_info', 'getChildHtml');
$tabsOrder = $helper->getConfig('pages/product_view/tabs_order');
$removedTabs = $helper->getConfig('pages/product_view/removed_tabs');
if ($removedTabs) {
    $removedTabs =  explode(',', str_replace(' ', '', $removedTabs));
    foreach ($detailedInfoGroup as $key => $name) {
        if (in_array($name, $removedTabs)) {
            unset($detailedInfoGroup[$key]);
        }
    }
}
if ($tabsOrder) {
    $tabsOrder = explode(',', str_replace(' ', '', $tabsOrder));
    foreach ($tabsOrder as $key => $name) {
        if (!in_array($name, $detailedInfoGroup)) {
            unset($tabsOrder[$key]);
        }
    }
    $detailedInfoGroup = array_unique(array_merge($tabsOrder, $detailedInfoGroup));
}
?>

<?php if ($detailedInfoGroup): ?>
    <div class="product info detailed">
        <?php $layout = $block->getLayout(); ?>
        <div class="product data items" id="<?= $uid ?>">
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php
                    $html = $layout->renderElement($name);
                    if (!trim($html)) {
                        continue;
                    }
                    $alias = $layout->getElementAlias($name);
                    $label = $block->getChildData($alias, 'title');
                ?>
                <div class="data item title"
                     aria-labeledby="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title"
                     data-role="collapsible" id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>">
                    <a class="data switch"
                       tabindex="-1"
                       data-toggle="switch"
                       href="#<?php /* @escapeNotVerified */ echo $alias; ?>"
                       id="tab-label-<?php /* @escapeNotVerified */ echo $alias;?>-title">
                        <?php /* @escapeNotVerified */ echo $label; ?>
                    </a>
                </div>
                <div class="data item content" id="<?php /* @escapeNotVerified */ echo $alias; ?>" data-role="content">
                    <?php /* @escapeNotVerified */ echo $html; ?>
                </div>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>

<script>
require(['jquery', 'tabs'], function($) {
    var $productTabs = $('#<?= $uid ?>');
    $.mage.tabs({"openedState":"active"}, $productTabs);
    var mageTabs = $productTabs.data('mageTabs');
    if (mageTabs) {
        var deskTabs = function() {
            mageTabs.options.collapsible = false;
            mageTabs._callCollapsible();
            if ($productTabs.find('[aria-selected="true"]').length == 0) {
                mageTabs.activate(0);
            }
        };
        var mobiTabs = function() {
            mageTabs.options.collapsible = true;
            mageTabs._callCollapsible();
        };
        if (window.innerWidth < 768) {
            mobiTabs();
        }
        $(window).on('cdz_desktop', deskTabs).on('cdz_mobile', mobiTabs);
    }
});
</script>