<?php 
/**
 * Sunbrains
 * Copyright (C) 2019 Sunbrains <info@sunbrains.com>
 *
 * @category Sunbrains
 * @package Sunbrains_SMSNotification
 * @copyright Copyright (c) 2019 Mage Delight (http://www.sunbrains.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Sunbrains <info@sunbrains.com>
 */
 
 $id = $this->getRequest()->getParam('entity_id');
$sms = $block->getSMSDetailsById($id);
echo '<table width="100%" border="1">';
foreach ($sms->getData() as $key => $value) {
	echo "<tr>";
	echo '<td class="fieldname">'.$key.'</td>';
	echo '<td>'.$value.'</td>';
	echo "</tr>";     	
}
echo '</table>';
?>

<style type="text/css">
	th, td {
 		 padding: 15px;
	}
	table, th, td {
  	 border-collapse: collapse;
	}
     .fieldname { text-transform: capitalize;}
</style>