<?php
/**
 * Copyright © 2017 Codazon, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$tabs = $block->getData('tabs_data');
$tabItems = json_decode($tabs   ->getData('items'), true);
?>

<?php if (count($tabItems)): ?>
<?php
$wrapClass = $tabs->getData('class');
$settings = $tabs->getData('settings');
$title = $tabs->getData('title');
$desc = $tabs->getData('desc');
$item = new \Magento\Framework\DataObject();
$align = ($tabs->getData('align') == 'center')?'md-center-tabs':'';
?>
<div class="cdz-tabs-wrap <?= $wrapClass ?>">
    <?php if ($title) : ?>
    <div class="cdz-block-title">
        <p class="b-title h2"><span><?= $title ?></span></p>
        <?php if ($desc) : ?>
        <p class="title-desc"><span><?= $desc ?></span></p>
        <?php endif ?>
    </div>
    <?php endif ?>
    <div class="cdz-block-content">
        <div class="cdz-tabs hidden" data-role="md-tabs" <?= $align ?>>
        <?php foreach ($tabItems as $itemData) : ?>
            <?php
                $item->setData($itemData);
                $icon = $item->getData('icon');
                $icon = $icon?"<i class=\"tab-icon fa {$icon}\"></i> ":'';
            ?>
            <div class="tab-item">
                <div class="tab-title"><?= $icon . $item->getData('title') ?></div>
                <div class="tab-content"><?= $item->getData('content'); ?></div>
            </div>
        <?php endforeach ?>
        </div>
    </div>
</div>
<?php endif ?>